### ISSUE TITLE
Rename AssetTransferAddress to AsssetAddress

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain-sdk-js#115]
I think `AssetTransferAddress` is too verbose. Why don't we simplify it to `AssetAddress`? The meaning is still clear.

**Comment by sgkim126** [comment]
We already have `AssetAddress` in CodeChain. I think it will be confusing.

**Comment by kseo** [comment]
@sgkim126 Is `AssetAddress` exposed to the SDK?

**Comment by sgkim126** [comment]
There is a no class named `AssetAddress`, but there are `getAssetAddress` which returns H256.
https://github.com/CodeChain-io/codechain-sdk-js/blob/4a8a79d2065678432d076e4c1e4e9af933bf2eb5/src/core/transaction/AssetMintTransaction.ts#L217
https://github.com/CodeChain-io/codechain-sdk-js/blob/6227fcad27f82be0001592f5264c5ff230804f7d/src/core/transaction/AssetTransferTransaction.ts#L247
