### ISSUE TITLE
Don't expose MemoryKeyStore

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain-sdk-js#133]
Use `ExternalKeyStore` by default and hide `MemoryKeyStore`.

**Comment by joojis** [comment]
Landed in https://github.com/CodeChain-io/codechain-sdk-js/commit/8a647cd7fe893e3cbf70866f9f5e8a544c492a8a and https://github.com/CodeChain-io/codechain-sdk-js/commit/db00c3909bc2fe302f141a9d735f0698ff76303b
