### ISSUE TITLE
Add "Hash" value to each transaction type

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-sdk-js#29]
I'd like to use defined "Block" type for DB document type. And I need "Hash" value for searching transaction by hash key.

**Comment by xpdlf1004** [comment]
Currently, a hash contains "value" object.

**Comment by joojis** [comment]
Merged: https://github.com/CodeChain-io/codechain-sdk-js/commit/d7dec38abf5f16df91351f72444ba1a7a3a6598a
