### ISSUE TITLE
Minting fails when the metadata includes some of Unicode characters

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-sdk-js#296]
https://saluki.codechain.io/explorer/tx/0x67cad8b6652520b90b18af962d51c4083e7669104de72937cf3d4dbe84ab6f98

**Comment by sgkim126** [comment]
I added test cases to guarantee that CodeChain handles single quotes.
https://github.com/CodeChain-io/codechain/pull/1125
By the way, I cannot find a single quotation on the metadata of the failed transaction.

**Comment by joojis** [comment]
Oh, I found that it actually was Unicode's single quote.
http://www.codetable.net/decimal/8217

**Comment by joojis** [comment]
@sgkim126 The single quotation was modified in the explorer.
![image](https://user-images.githubusercontent.com/9711879/51297810-06b9b980-1a33-11e9-8522-22fd9b13cf27.png)

**Comment by joojis** [comment]
I'm closing this because it's not reproducible at the latest version.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/9711879/53388803-f56bb180-39cf-11e9-9990-1025db1999c9.png">
