### ISSUE TITLE
Refactor Asset.transfer() to Asset.createTransferTransaction()

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-sdk-js#73]
Current:
```
var myAsset = ...
var transferTransaction = myAsset.transfer([{
    address: addressAlice
    amount: 10
}, {
    address: addressBob
    amount: 20
}])
```

Proposal:
```
var myAsset = ...
var transferTransaction = myAsset.createTransferTransaction({
    recipients: [{
        address: addressAlice
        amount: 10
    }, {
        address: addressBob
        amount: 20
    }]
})
```

**Comment by sgkim126** [comment]
I agree with renaming it to `createTransferTransaction`. But I'm not sure about the named parameter.
Isn't it obvious that the parameter is recipients?

**Comment by sgkim126** [comment]
Are there any optional parameters?

**Comment by joojis** [comment]
@sgkim126 Not now, but nonce should be added I think.

**Comment by joojis** [comment]
Patch: https://github.com/CodeChain-io/codechain-sdk-js/commit/8dbbe2672d2b96d59ed87b230c6e48cc66a42858
